version: "3"
services:
  static_server:
    container_name: static_server
    image: centos-tomcat:latest
  persistence_server:
    container_name: persistence_server
    image: centos-tomcat:latest
  appserver1:
    container_name: appserver1
    image: centos-tomcat:latest
  appserver2:
    container_name: appserver2
    image: centos-tomcat:latest
  appserver3:
    container_name: appserver3
    image: centos-tomcat:latest
  ansible:
    container_name: ansible
    image: centos-ansible:latest
    volumes:
    - /Users/caozhi/home/twc-data/project/devops-all-in-one:/root/deploy/mnt
    depends_on:
    - static_server
    - persistence_server
    - appserver1
    - appserver2
    - appserver3
    links:
    - static_server
    - persistence_server
    - appserver1
    - appserver2
    - appserver3


## todo: 
## 1. 改名字
### docker compose 里触发执行一些命令，或者在外部调compose的时候去触发执行，做：生成ssh-keygen, copy-id