node {
    def mvnHome
    stage('Preparation') { // Sync codes
        git 'git@github.com:caozhi/sample-project.git'
        mvnHome = tool 'M3'
    }
   stage('Build') {
        // update build number
            
        // submit to git
            
        //
        // Run the maven build
        sh "'${mvnHome}/bin/mvn' -Dmaven.test.failure.ignore clean install"
    }
    stage('Results') {
        junit '**/target/surefire-reports/TEST-*.xml'
        archive 'target/*.war'
    }
}